import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.scss";
import { Header } from "@/components/Header/Header";

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={beVietnamPro.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
